apiVersion: v1
kind: Service
metadata:
  name: gerrit-mysql-service
spec:
  selector:
    app: gerrit-mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30066
  type: NodePort