apiVersion: v1
kind: Service
metadata:
  name: gerrit-service
spec:
  selector:
    app: gerrit
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30068
  - name: ssh
    protocol: TCP
    port: 29418
    targetPort: 29418
    nodePort: 30067
  type: NodePort